language: python
python:
  - "2.7"
env: DB=postgres
# command to install dependencies
install: 
    - pip install -r requirements.txt
# commands before running tests
before_script:
  - psql -c 'create database photoapp;' -U postgres
  - psql -c 'create role mark;'
# command to run tests
script:
    - python django_photos/manage.py test