from django.conf.urls import patterns, url
from django.contrib.auth.views import login, logout

urlpatterns = patterns(
    'photoapp.views',
    url(
        r'^$',
        'index_view',
        name='index',
        ),
    url(
        r'^home/$',
        'home_view',
        name='home',
        ),
    url(
        r'^album/(\d+)/$',
        'album_view',
        name='album_specific',
        ),
    url(
        r'^album/(\d+)/photo/(\d+)/$',
        'photo_view',
        name='photo_specific',
        ),
    url(
        r'^tag/(\w+)/$',
        'tag_view',
        name='tag_specific',
        ),
    url(
        r'^login/$',
        login,
        name='login',
        ),
    url(
        r'^logout/$',
        logout,
        name='logout',
        ),
    url(
        r'^new_album/$',
        'new_album',
        name='new_album',
        ),
    url(
        r'^album/(\d+)/new_photo/$',
        'new_photo',
        name='new_photo',
        ),
    url(
        r'^album/(\d+)/photo/(\d+)/new_tag/$',
        'new_tag',
        name='new_tag',
        ),
)
